EN_TCHECK_SYSTEM_PROMPT = ...  # TODO

EN_TCHECK_USER_PROMPT = ...  # TODO
EN_TCHECK_ASSISTANT_PROMPT = ...  # TODO

RU_TCHECK_SYSTEM_PROMPT = ...  # TODO
RU_TCHECK_USER_PROMPT = ...  # TODO
RU_TCHECK_ASSISTANT_PROMPT = ...  # TODO
