services:

  # Database - Neo4j
  neo4j:
    container_name: personalai_mmenschikov_neo4j
    user: "4200235:4200235"
    image: neo4j:5.21.0-enterprise
    hostname: personalai_mmenschikov_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ../neo4j_volume/data:/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G

  workspace:
    image: m.menschikov/workspace:v1
    container_name: personalai_mmenschikov_worksapce
    hostname: worksapceservice
    ports:
      - "10888:10888"
    volumes:
      - ../:/home/m.menschikov/workspace/personal_ai
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 32G
        reservations:
          cpus: '8'
          memory: 24G
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

  empty_workspace:
    image: m.menschikov/empty_workspace:v1
    container_name: personalai_mmenschikov_empty_worksapce
    hostname: emptyworksapceservice
    ports:
      - "10888:10888"
    volumes:
      - ../:/home/workspace
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 32G
        reservations:
          cpus: '8'
          memory: 24G
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]


  ollama_agent:
    #image: m.menschikov/agent_service:v1
    image: ollama/ollama:latest
    container_name: personalai_mmenschikov_ollama_service
    hostname: ollamaservice
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_DEBUG=1
    volumes:
      - ../ollama_volume:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G
          devices:
            - driver: nvidia
              device_ids: ['2']
              capabilities: [gpu]
