version: "3"
services:

  aerospike_golden_gigachat:
    container_name: personalai_aerospike
    hostname: aerospikelservice
    image: m.menschikov/aerospike:ee-7.1.0.6_1
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ../aerospike_volumes/golden_gigachat/data:/opt/aerospike/data
      - ../aerospike_volumes/configs:/etc/aerospike
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G

  aerospike_built_gigachat:
    container_name: personalai_aerospike
    hostname: aerospikelservice
    image: m.menschikov/aerospike:ee-7.1.0.6_1
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - ../aerospike_volumes/built_gigachat/data:/opt/aerospike/data
      - ../aerospike_volumes/configs:/etc/aerospike
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G

  # Database - Neo4j
  neo4j:
    container_name: personalai_mmenschikov_neo4j
    image: neo4j:5.21.0-enterprise
    hostname: personalai_mmenschikov_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ../neo4j_volume/data:/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 4G

  workspace:
    image: m.menschikov/workspace:v1
    container_name: personalai_mmenschikov_worksapce
    hostname: worksapceservice
    ports:
      - "10888:10888"
    volumes:
      - ./:/workspace
    depends_on:
      - aerospike_built_gigachat
      - neo4j
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 32G
        reservations:
          cpus: '8'
          memory: 24G
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]

  isolated_environment:
    image: m.menschikov/empty_workspace:v1
    container_name: personalai_mmenschikov_isolated_env
    hostname: isolated_env
    volumes:
      - ./src:/home/workspace/src
      - ./data:/home/workspace/data
      - ./models:/home/workspace/models
      - ./notebooks:/home/worksapce/notebooks
