from ...prompts.memory_extraction import \
    TRIPLETS_EXTRACTION_PROMPT_EN_USER, TRIPLETS_EXTRACTION_PROMPT_EN_SYSTEM, \
    TRIPLETS_EXTRACTION_PROMPT_RU_USER, TRIPLETS_EXTRACTION_PROMPT_RU_SYSTEM, \
    THESISES_EXTRACTION_PROMPT_EN_USER, THESISES_EXTRACTION_PROMPT_EN_SYSTEM, \
    THESISES_EXTRACTION_PROMPT_RU_USER, THESISES_EXTRACTION_PROMPT_RU_SYSTEM

from ...parsers.memory_extraction import mem_custom_triplet_parse_func, mem_custom_thesis_parse_func

# triplet-prompts
MEM_EXTRACT_TRIPLET_SYSTEM_PROMPT = {
    'ru': TRIPLETS_EXTRACTION_PROMPT_RU_SYSTEM,
    'en': TRIPLETS_EXTRACTION_PROMPT_EN_SYSTEM}
MEM_EXTRACT_TRIPLET_USER_PROMPT = {
    'ru': TRIPLETS_EXTRACTION_PROMPT_RU_USER,
    'en': TRIPLETS_EXTRACTION_PROMPT_EN_USER}

# triplet-parsers
MEM_TRIPLET_PARSE_FUNC = {
    'ru': mem_custom_triplet_parse_func,
    'en': mem_custom_triplet_parse_func
}

# thesis-prompts
MEM_EXTRACT_THESIS_SYSTEM_PROMPT = {
    'ru': THESISES_EXTRACTION_PROMPT_RU_SYSTEM,
    'en': THESISES_EXTRACTION_PROMPT_EN_SYSTEM}
MEM_EXTRACT_THESIS_USER_PROMPT = {
    'ru': THESISES_EXTRACTION_PROMPT_RU_USER,
    'en': THESISES_EXTRACTION_PROMPT_EN_USER}

# thesis-parsers
MEM_THESIS_PARSE_FUNC = {
    'ru': mem_custom_thesis_parse_func,
    'en': mem_custom_thesis_parse_func
}

MEM_EXTRACT_LOG_PATH = "log/extract"
