from ...prompts.memory_extraction import \
    TRIPLETS_EXTRACTION_PROMPT_EN_USER, TRIPLETS_EXTRACTION_PROMPT_EN_SYSTEM, \
    TRIPLETS_EXTRACTION_PROMPT_RU_USER, TRIPLETS_EXTRACTION_PROMPT_RU_SYSTEM, \
    THESISES_EXTRACTION_PROMPT_EN_USER, THESISES_EXTRACTION_PROMPT_EN_SYSTEM, \
    THESISES_EXTRACTION_PROMPT_RU_USER, THESISES_EXTRACTION_PROMPT_RU_SYSTEM

# triplet-prompts
MEM_EXTRACT_TRIPLET_SYSTEM_PROMPT = {
    'ru': TRIPLETS_EXTRACTION_PROMPT_RU_SYSTEM,
    'en': TRIPLETS_EXTRACTION_PROMPT_EN_SYSTEM}
MEM_EXTRACT_TRIPLET_USER_PROMPT = {
    'ru': TRIPLETS_EXTRACTION_PROMPT_RU_USER,
    'en': TRIPLETS_EXTRACTION_PROMPT_EN_USER}

# thesis-prompts
MEM_EXTRACT_THESIS_SYSTEM_PROMPT = {
    'ru': THESISES_EXTRACTION_PROMPT_RU_SYSTEM,
    'en': THESISES_EXTRACTION_PROMPT_EN_SYSTEM}
MEM_EXTRACT_THESIS_USER_PROMPT = {
    'ru': THESISES_EXTRACTION_PROMPT_RU_USER,
    'en': THESISES_EXTRACTION_PROMPT_EN_USER}

MEM_EXTRACT_LOG_PATH = "log/extract"