EN_QEXPAN_SYSTEM_PROMPT = ...  # TODO

EN_QEXPAN_USER_PROMPT = ...  # TODO
EN_QEXPAN_ASSISTANT_PROMPT = ...  # TODO

RU_QEXPAN_SYSTEM_PROMPT = ...  # TODO
RU_QEXPAN_USER_PROMPT = ...  # TODO
RU_QEXPAN_ASSISTANT_PROMPT = ...  # TODO
