EN_DC_SYSTEM_PROMPT = ... # TODO
EN_DC_USER_PROMPT = ... # TODO
EN_DC_ASSISTANT_PROMPT = ... # TODO

RU_DC_SYSTEM_PROMPT = ... # TODO
RU_DC_USER_PROMPT = ... # TODO
RU_DC_ASSISTANT_PROMPT = ... # TODO