EN_DCLS_SYSTEM_PROMPT = ... # TODO
EN_DCLS_USER_PROMPT = ... # TODO
EN_DCLS_ASSISTANT_PROMPT = ... # TODO

RU_DCLS_SYSTEM_PROMPT = ... # TODO
RU_DCLS_USER_PROMPT = ... # TODO
RU_DCLS_ASSISTANT_PROMPT = ... # TODO