EN_SWREMV_SYSTEM_PROMPT = ... # TODO
EN_SWREMV_USER_PROMPT = ... # TODO
EN_SWREMV_ASSISTANT_PROMPT = ... # TODO

RU_SWREMV_SYSTEM_PROMPT = ... # TODO
RU_SWREMV_USER_PROMPT = ... # TODO
RU_SWREMV_ASSISTANT_PROMPT = ... # TODO
