EN_ANSWGEN_SYSTEM_PROMPT = ... # TODO
EN_ANSWGEN_USER_PROMPT = ... # TODO
EN_ANSWGEN_ASSISTANT_PROMPT = ... # TODO

RU_ANSWGEN_SYSTEM_PROMPT = ... # TODO
RU_ANSWGEN_USER_PROMPT = ... # TODO 
RU_ANSWGEN_ASSISTANT_PROMPT = ... # TODO