EN_CASUMM_SYSTEM_PROMPT = ... # TODO
EN_CASUMM_USER_PROMPT = ... # TODO
EN_CASUMM_ASSISTANT_PROMPT = ... # TODO

RU_CASUMM_SYSTEM_PROMPT = ... # TODO
RU_CASUMM_USER_PROMPT = ... # TODO 
RU_CASUMM_ASSISTANT_PROMPT = ... # TODO