EN_LCHECK_SYSTEM_PROMPT = ...  # TODO

EN_LCHECK_USER_PROMPT = ...  # TODO
EN_LCHECK_ASSISTANT_PROMPT = ...  # TODO

RU_LCHECK_SYSTEM_PROMPT = ...  # TODO
RU_LCHECK_USER_PROMPT = ...  # TODO
RU_LCHECK_ASSISTANT_PROMPT = ...  # TODO
