EN_SUBASUMM_SYSTEM_PROMPT = ... # TODO
EN_SUBASUMM_USER_PROMPT = ... # TODO
EN_SUBASUMM_ASSISTANT_PROMPT = ... # TODO

RU_SUBASUMM_SYSTEM_PROMPT = ... # TODO
RU_SUBASUMM_USER_PROMPT = ... # TODO
RU_SUBASUMM_ASSISTANT_PROMPT = ... # TODO