EN_ENHCLS_SYSTEM_PROMPT = ... # TODO
EN_ENHCLS_USER_PROMPT = ... # TODO
EN_ENHCLS_ASSISTANT_PROMPT = ... # TODO

RU_ENHCLS_SYSTEM_PROMPT = ... # TODO
RU_ENHCLS_USER_PROMPT = ... # TODO 
RU_ENHCLS_ASSISTANT_PROMPT = ... # TODO