EN_PLANENH_SYSTEM_PROMPT = ... # TODO
EN_PLANENH_USER_PROMPT = ... # TODO
EN_PLANENH_ASSISTANT_PROMPT = ... # TODO

RU_PLANENH_SYSTEM_PROMPT = ... # TODO
RU_PLANENH_USER_PROMPT = ... # TODO 
RU_PLANENH_ASSISTANT_PROMPT = ... # TODO