DATASET_NAME: 'diaasqa' # TO CHANGE
KNOWLEDGE_GRAPH_NAME: 'qwen25_060325_v1prompts' # TO CHANGE

KGS_BASE_PATH: '/home/dzigen/Desktop/PersonalAI/Personal-AI/data/knowledge_graphs'
BASE_PERSONALAI_DIR: '/home/dzigen/Desktop/PersonalAI/Personal-AI'

KG_DIR_STRUCT:
  embeddings_dir_name: embeddings_part
  graph_dir_name: graph_part
  cache_dir_name:
    base: kv_cache
    persistant: persistent_volume
    ram: ram_volume
  tmp_triplets_dir_name: tmp_extracted_triplets
