DATASET_NAME: 'hotpotqa_distractor_validation' # TO CHANGE
KNOWLEDGE_GRAPH_NAME: 'qwen25_080325_v2prompts' # TO CHANGE

########## HARDCODED PARAMS ##########

KG_DIR_STRUCT:
  embeddings_dir_name: embeddings_part
  graph_dir_name: graph_part
  cache_dir_name:
    base: kv_cache
    persistant: persistent_volume
    ram: ram_volume

WORKSPACE_CONTAINER_DIRS:
  base_path: '/home/workspace'
  kg: 'data/knowledge_graphs'
  qa_datasets: 'data/qa_datasets'
  notebooks: 'notebooks'
  src: 'src'
  models: 'models'
