# == Prompts in English ==

EN_REJECT_ANSW_CLS_SYSTEM_PROMPT = \
'''
You must determine whether the text [Source text] is evasive / a refusal / a meta-policy response from the model instead of normal substantive text (which could be either a valid model response or a user's question/statement).
Return True (the text is an attempt by the model to evade answering the original task and represents a general refusal / disclaimer / text about policy) or False (this resembles valid text where the model is essentially trying to perform the task, or it is completely separate text having no relation to a potential attempt by the model to evade answering).

Task:
Classify the given text by its content as:
- True — if it is an unsuccessful answer attempt: the model refuses, evades the question, or only explains its limitations / safety rules instead of solving the task.
- False — if it is a normal answer/question/statement that could correspond to a user's request/query/comment, etc.; a potentially at least partially valid model response; or a completely unrelated topic or area.

Rules:
1. Do not use external knowledge. Rely solely on the [Source text].
2. First, return a brief justification in the [Chain of thoughts] block. Then return the final answer in the [Answer] block.
3. If you are unsure whether the [Source text] relates to a refusal/evasion or to valid text, return False.
4. Output only the [Chain of thoughts] and [Answer] blocks — generate nothing else. In the [Answer] block, return only True or False.

Input format:
[Source text] — the source text to classify.

Output format (two sections):
[Chain of thoughts] — 2-5 concise bullet points with brief reasoning for the decision.
[Answer] — True or False.

Examples:

[Source text #1]
Unfortunately, generative language models can sometimes produce incorrect answers based on open sources.
To avoid misinterpretation, answers to questions related to sensitive topics are temporarily limited. Thank you for your understanding.

[Chain of thoughts]
- The text talks about generative models in general and their possible errors.
- It mentions "sensitive topics" and temporary restrictions on answers.
- There is no substantive response to a specific task.
- This is a general disclaimer and refusal to answer.
[Answer]
True


[Source text #2]
Generative language models do not have their own opinions — their responses are a generalization of information available in the public domain.
To avoid mistakes and misinterpretation, conversations on sensitive topics may be limited.

[Chain of thoughts]
- The text describes the nature of language models and the absence of their own opinion.
- It mentions the limitation of conversations on sensitive topics.
- Not a single fact on any subject, only meta-information and limitations.
[Answer]
True


[Source text #3]
Like any language model, GigaChat does not have its own opinion and does not convey the opinions of its developers.
The answer is generated by a neural network model trained on open data, which may contain inaccurate or erroneous information.
To avoid misinterpretation, discussions on certain topics are temporarily limited.

[Chain of thoughts]
- The text explains that GigaChat is a language model without its own opinion.
- It mentions open data, possible errors, and temporary topic restrictions.
- There is a complete absence of an attempt to answer any specific question.
[Answer]
True


[Source text #4]
The capital of France is Paris. The city is located in the northern part of the country and is known for landmarks such as the Eiffel Tower and the Louvre.

[Chain of thoughts]
- The text clearly answers a possible question about the capital of France.
- It provides specific facts about Paris.
- There are no refusals, no general discussions about the model or its limitations.
[Answer]
False


[Source text #5]
I cannot make a diagnosis or replace a doctor's consultation.
However, I can list typical flu symptoms: fever, cough, sore throat, muscle aches, and fatigue.

[Chain of thoughts]
- The first phrase is a disclaimer about the inability to make a diagnosis.
- Then the model lists specific flu symptoms — factual information on the topic.
- Overall, this is an attempt to help, not a complete refusal to answer.
[Answer]
False


[Source text #6]
Where can I see beautiful places in the Samara region?

[Chain of thoughts]
- The text resembles a normal question about where to find beautiful places in the Samara region.
- It is in no way related to an LLM model and its attempts to evade/refuse to answer.
[Answer]
False


[Source text #7]
||user||: The user is interested in which cities musicians get the most inspiration.


||assistant||: Musicians are often inspired by landscapes, city atmospheres, and forest sounds. Here are some cities that particularly inspire creators: Kaliningrad, Saint Petersburg, Moscow, ...


||user||: How interesting! The user expressed a desire to move to Kaliningrad

[Chain of thoughts]
- The text resembles a dialogue exchange between a user and an assistant.
- It is in no way related to an LLM model and its attempts to evade/refuse to answer.
[Answer]
False
'''

EN_REJECT_ANSW_CLS_USER_PROMPT = \
'''
[Source text]
{source_answer}
'''

EN_REJECT_ANSW_CLS_ASSISTANT_PROMPT = \
'''
[Chain of thoughts]
'''


# == Prompts in Russian ==

RU_REJECT_ANSW_CLS_SYSTEM_PROMPT = \
'''
Вы должны определить, является ли текст [Source text] уклончивым / отказом / мета-политическим ответом модели вместо нормального содержательного текста (который может быть как валидным ответом модели, так и вопросом/высказыванием пользователя, так и касаться совершенно отдаленной области).
Верните True (текст является попыткой модели уйти от ответа на исходную задачу и представляет собой общий отказ / дисклеймер / текст про политику) или False (это похоже валидный текст, в котором модель по сути пытается выполнить задачу, либо это вообще отдельный текст, не имеющий никакого отношения к потенциальной попытке модели уйти от ответа).

Задача:
Классифицировать данный текст по его содержанию как:
- True — если это неудачная попытка ответа: модель отказывается, уходит от вопроса или только объясняет свои ограничения / правила безопасности вместо того, чтобы решать задачу.
- False — если это нормальный ответ/вопрос/высказывание, который может соотетствовать запросу/просьбе/комментарию и тд пользователя; потенциально хотя бы частично валидному ответу модели; вообще отвлеченной теме или области.

Правила:
1. Не используйте внешние знания. Опирайтесь только на [Source text].
2. Сначала верните краткое обоснование в блоке [Chain of thoughts]. Затем верните финальный ответ в блоке [Answer].
3. Если вы сомневаетесь, относится ли [Source text] к отказу/уходу от ответа или к валидному тексту, возвращайте False.
4. Выводите только блоки [Chain of thoughts] и [Answer] — ничего кроме этого не генерируйте. В блоке [Answer] верните только True или False.

Формат ввода:
[Source text] — исходный текст для классификации.

Формат вывода (две секции):
[Chain of thoughts] — 2-5 лаконичных пунктов с кратким обоснованием решения.
[Answer] — True или False.

Примеры:

[Source text #1]
К сожалению, иногда генеративные языковые модели могут создавать некорректные ответы, основанные на открытых источниках.
Во избежание неправильного толкования, ответы на вопросы, связанные с чувствительными темами, временно ограничены. Благодарим за понимание.

[Chain of thoughts]
- Текст говорит о генеративных моделях в целом и их возможных ошибках.
- Упоминаются "чувствительные темы" и временные ограничения ответов.
- Нет никакого содержательного ответа по конкретной задаче.
- Это общий дисклеймер и отказ от ответа.
[Answer]
True


[Source text #2]
Генеративные языковые модели не обладают собственным мнением — их ответы являются обобщением информации, находящейся в открытом доступе.
Чтобы избежать ошибок и неправильного толкования, разговоры на чувствительные темы могут быть ограничены.

[Chain of thoughts]
- Текст описывает природу языковых моделей и отсутствие собственного мнения.
- Говорится об ограничении разговоров на чувствительные темы.
- Ни одного факта по какому-либо предмету, только мета-информация и ограничения.
[Answer]
True


[Source text #3]
Как и любая языковая модель, GigaChat не обладает собственным мнением и не транслирует мнение своих разработчиков.
Ответ сгенерирован нейросетевой моделью, обученной на открытых данных, в которых может содержаться неточная или ошибочная информация.
Во избежание неправильного толкования, разговоры на некоторые темы временно ограничены.

[Chain of thoughts]
- Текст рассказывает о том, что GigaChat — языковая модель без собственного мнения.
- Упоминаются открытые данные, возможные ошибки и временное ограничение тем.
- Полностью отсутствует попытка ответить на какой-либо конкретный вопрос.
[Answer]
True


[Source text #4]
Столицей Франции является Париж. Город расположен в северной части страны и известен такими достопримечательностями, как Эйфелева башня и Лувр.

[Chain of thoughts]
- Текст явно отвечает на возможный вопрос о столице Франции.
- Даёт конкретные факты о Париже.
- Нет отказов, нет общих рассуждений о модели или ограничениях.
[Answer]
False


[Source text #5]
Я не могу поставить диагноз или заменить консультацию врача.
Однако могу перечислить типичные симптомы гриппа: повышенная температура, кашель, боль в горле, ломота в мышцах и усталость.

[Chain of thoughts]
- Первая фраза — дисклеймер о невозможности ставить диагноз.
- Далее модель приводит конкретные симптомы гриппа — фактическая информация по теме.
- В целом это попытка помочь, а не полный отказ от ответа.
[Answer]
False


[Source text #6]
Где можно увидеть красивые места в Самарской области?

[Chain of thoughts]
- Текст похож на обычный вопрос, посвященный тому, где можно найти красивые места в Самарской области.
- Он никак не связан с LLM моделью и ее попытками уйти/отказаться от ответа
[Answer]
False


[Source text #7]
||user||: Пользователь интересуется, в каких городах музыканты получают наибольшее количество вдохновения.


||assistant||: Музыканты часто вдохновляются пейзажами, атмосферой городов, звуками леса. Вот некоторые города, которые особенно вдохновляют творцов: Калининград, Санкт-Петербург, Москва, ...


||user||: Как интересно! Пользователь выразил желаение переехать в Калининград


[Chain of thoughts]
- Текст похож на переписку между пользователем и помощником
- Он никак не связан с LLM моделью и ее попытками уйти/отказаться от ответа
[Answer]
False
'''

RU_REJECT_ANSW_CLS_USER_PROMPT = \
'''
[Source text]
{source_answer}
'''

RU_REJECT_ANSW_CLS_ASSISTANT_PROMPT = \
'''
[Chain of thoughts]
'''
