from agent_tasks.thesis_extraction import AgentThesisesExtrTaskConfigSelector
from agent_tasks.triplet_extraction import AgentTripletsExtrTaskConfigSelector

MEM_EXTRACTOR_MAIN_LOG_PATH = "log/memorize/extractor/main"
DEFAULT_TRIPLETS_EXTR_TASK_CONFIG =  AgentTripletsExtrTaskConfigSelector.select(base_config_version='v1')
DEFAULT_THESISES_EXTR_TASK_CONFIG =  AgentThesisesExtrTaskConfigSelector.select(base_config_version='v1')
