EN_ENTEXTR_SYSTEM_PROMPT = ... # TODO
EN_ENTEXTR_USER_PROMPT = ... # TODO
EN_ENTEXTR_ASSISTANT_PROMPT = ... # TODO

RU_ENTEXTR_SYSTEM_PROMPT = ... # TODO 
RU_ENTEXTR_USER_PROMPT = ... # TODO 
RU_ENTEXTR_ASSISTANT_PROMPT = ... # TODO