EN_PLANINIT_SYSTEM_PROMPT = ... # TODO
EN_PLANINIT_USER_PROMPT = ... # TODO
EN_PLANINIT_ASSISTANT_PROMPT = ... # TODO

RU_PLANINIT_SYSTEM_PROMPT = ... # TODO
RU_PLANINIT_USER_PROMPT = ... # TODO 
RU_PLANINIT_ASSISTANT_PROMPT = ... # TODO