EN_ANSWCLS_SYSTEM_PROMPT = ... # TODO
EN_ANSWCLS_USER_PROMPT = ... # TODO
EN_ANSWCLS_ASSISTANT_PROMPT = ... # TODO

RU_ANSWCLS_SYSTEM_PROMPT = ... # TODO
RU_ANSWCLS_USER_PROMPT = ... # TODO 
RU_ANSWCLS_ASSISTANT_PROMPT = ... # TODO