EN_QGEN_SYSTEM_PROMPT = ... # TODO
EN_QGEN_USER_PROMPT = ... # TODO
EN_QGEN_ASSISTANT_PROMPT = ... # TODO

RU_QGEN_SYSTEM_PROMPT = ... # TODO
RU_QGEN_USER_PROMPT = ... # TODO 
RU_QGEN_ASSISTANT_PROMPT = ... # TODO