EN_CQGEN_SYSTEM_PROMPT = ... # TODO
EN_CQGEN_USER_PROMPT = ... # TODO
EN_CQGEN_ASSISTANT_PROMPT = ... # TODO

RU_CQGEN_SYSTEM_PROMPT = ... # TODO
RU_CQGEN_USER_PROMPT = ... # TODO 
RU_CQGEN_ASSISTANT_PROMPT = ... # TODO