EN_QD_SYSTEM_PROMPT = ... # TODO 
EN_QD_USER_PROMPT = ... # TODO 
EN_QD_ASSISTANT_PROMPT = ... # TODO

RU_QD_SYSTEM_PROMPT = ... # TODO
RU_QD_USER_PROMPT = ... # TODO
RU_QD_ASSISTANT_PROMPT = ... # TODO