EN_QDECOMP_SYSTEM_PROMPT = ... # TODO 
EN_QDECOMP_USER_PROMPT = ... # TODO 
EN_QDECOMP_ASSISTANT_PROMPT = ... # TODO

RU_QDECOMP_SYSTEM_PROMPT = ... # TODO
RU_QDECOMP_USER_PROMPT = ... # TODO
RU_QDECOMP_ASSISTANT_PROMPT = ... # TODO