EN_GRAMCHECK_SYSTEM_PROMPT = ... # TODO

EN_GRAMCHECK_USER_PROMPT = ... # TODO
EN_GRAMCHECK_ASSISTANT_PROMPT = ... # TODO

RU_GRAMCHECK_SYSTEM_PROMPT = ... # TODO
RU_GRAMCHECK_USER_PROMPT = ... # TODO
RU_GRAMCHECK_ASSISTANT_PROMPT = ... # TODO
