from ..cases import ZERO_NESTED_CONFIGS, ONE_NESTED_CONFIGS, TWO_NESTED_CONFIGS, \
    THREE_NESTED_CONFIGS, FOUR_NESTED_CONFIGS, FIVE_NESTED_CONFIGS, \
        SIX_NESTED_CONFIGS, SEVEN_NESTED_CONFIGS

GROUPED_CONFIGS = [
    ZERO_NESTED_CONFIGS, ONE_NESTED_CONFIGS, TWO_NESTED_CONFIGS,
    THREE_NESTED_CONFIGS, FOUR_NESTED_CONFIGS, FIVE_NESTED_CONFIGS,
    SIX_NESTED_CONFIGS, SEVEN_NESTED_CONFIGS
]

SAVE_TEST_CASES = []
for i, configs_group in enumerate(GROUPED_CONFIGS):
    for config in configs_group:
        SAVE_TEST_CASES.append([config, i])
